cobot.createconnectionjson.url=http://localhost:9777/api/job/createjob
cobot.cliRecordconnectionJSONUrl.url=http://localhost:9777/api/job/cli/run
sahi.recorder.url=http://localhost:9999/_s_/spr/launchController.htm?controllerType=WINDOWS
cobot.server.url: http://localhost:8080/
cobot.server.heartbeat.interval: 180000
cobot.agent.id : SAVIYNT005

sendSignal.root.dir=C:/dump/scripts/agent/
security.oauth2.client.clientId: 0oa5i8reazZPf73Ty4x6
security.oauth2.client.clientSecret: P09t3AylXs1hlMBPUOkr_UIqnkBZIbJ-QAhBXK-_
security.oauth2.resource.tokenInfoUri: https://dev-805403.okta.com/oauth2/default/v1/introspect

secclient.oauth2.client.grantType: client_credentials
secclient.oauth2.client.clientId: 0oa5i8reazZPf73Ty4x6
secclient.oauth2.client.clientSecret: P09t3AylXs1hlMBPUOkr_UIqnkBZIbJ-QAhBXK-_
secclient.oauth2.client.accessTokenUri: https://dev-805403.okta.com/oauth2/default/v1/token
secclient.oauth2.client.scope: custom_mod

drivepath.separator: false
server.port=9777
scripts.dir=C:/dump/scripts/agent/
sahi.root.dir=C:/Users/HP/sahi
agent.installation.path:C:/Program Files/Identity Bot Agent/
agent.image.path:C:/Users/Admin/Downloads/connectorbot/agent/bluezone_Objects/
video.record=off

cli.errors = ACCESS_DENIED:Access denied for user;NOT_RECOGNIZED_COMMAND:is not recognized as an internal or external command;UNKNOWN_DATABASE:Unknown database

cobot.status.callback.url=http://localhost:8080/api/job/updatestatus

variable.commandline.exe= cmdd.exe

# logging level
logging.level.org.springframework=INFO
logging.level.com.peddle.digitals.cobot.agent=DEBUG

bot.agent.status=1
scripts.store=local
s3.access_key=
s3.secret_key=
cli.scriptType=CLI
pywinauto.recorder.path = D:/peddle/pywinauto_recorder-master/pywinauto_recorder-master

testbot.userid =chette.rajkumar@gmail.com
testbot.password =123456